services:
  qc.sty_sloppy-plum-gharial:
    command: sleep 6000000
    image: cytopia/jsonlint
    entrypoint: /bin/sh
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
